# Umar Jan 101270578
# Tutorial 5, Ex. B
import random
#rps
#input
def rps():
    playermove = int(input("1 for rock, 2 for paper, 3 for scissors"))
    #random generated by computer
    compmove = random.randint(1,3)
    if playermove == compmove:
        print("draw")
    elif playermove == 1 and compmove ==3:
        print("player wins")
    elif playermove == 1 and compmove == 2:
        print("AI wins")
    if playermove == 2 and compmove == 1:
        print("player wins")
    elif playermove == 2 and compmove == 3:
        print("AI wins")
    elif playermove == 3 and compmove == 1:
        print("player wins")
    elif playermove == 3 and compmove ==2:
        print("AI wins")
    if playermove<1 or playermove>3:
        print("invalid input resetting.....")
        return rps()
    cont = input("Would you like to continue playing? (enter yes to confirm)").upper()
    if cont == "YES":
        return rps()

board = ["-", "-", "-","-", "-", "-","-", "-", "-"] #boardsetup
player1 = "X"
winner = None
flag = True

# visual game board 3x3
def printBoard(board):
    print(board[0] + " | " + board[1] + " | " + board[2]) #making visual board
    print("-------")
    print(board[3] + " | " + board[4] + " | " + board[5])
    print("-------")
    print(board[6] + " | " + board[7] + " | " + board[8])


# takes the player's move
def playerInput(board):
    playermove = int(input("Select a spot 1-9: ")) -1
    if board[playermove] == "-":
        board[playermove] = player1
    else:
        print("AI has claimed that spot")

# checking for wins horizontally, vertically, and diagonally
def horizontalwin(board):
    global winner
    if board[0] == board[1] == board[2] and board[0] != "-":
        winner = board[0] #since board 0 is across so doesnt matter if board 0,1,2 same thing
        return True
    elif board[3] == board[4] == board[5] and board[3] != "-":
        winner = board[3]
        return True
    elif board[6] == board[7] == board[8] and board[6] != "-":
        winner = board[6]
        return True

def verticalwin(board):
    global winner
    if board[0] == board[3] == board[6] and board[0] != "-":
        winner = board[0]
        return True
    elif board[1] == board[4] == board[7] and board[1] != "-":
        winner = board[1]
        return True
    elif board[2] == board[5] == board[8] and board[2] != "-":
        winner = board[2]
        return True


def diagonalwin(board):
    global winner
    if board[0] == board[4] == board[8] and board[0] != "-":
        winner = board[0]
        return True
    elif board[2] == board[4] == board[6] and board[4] != "-":
        winner = board[2]
        return True


def ifwin(board):
    global flag
    if horizontalwin(board):
        printBoard(board)
        print("the winner is ",  winner)
        if winner == "X":
            print("congrats on winning")
        else:
            print("Better luck next time")
        flag = False

    elif verticalwin(board):
        printBoard(board)
        print("the winner is ", winner)
        if winner == "X":
            print("congrats on winning")
        else:
            print("Better luck next time")
        flag = False

    elif diagonalwin(board):
        printBoard(board)
        print("the winner is ", winner)
        if winner == "X":
            print("congrats on winning")
        else:
            print("Better luck next time")
        flag = False


def tiegame(board):
    global flag
    if "-" not in board:
        printBoard(board)
        print("tie game")
        flag = False


# switch from user to AI
def switchPlayer():
    global player1
    if player1 == "X":
        player1 = "O"
    else:
        player1 = "X"


def computer(board):
    while player1 == "O":
        position = random.randint(0, 8)
        if board[position] == "-":
            board[position] = "O"
            switchPlayer()
def tts(board):
    printBoard(board)
    playerInput(board)
    ifwin(board)
    tiegame(board)
    switchPlayer()
    computer(board)
    ifwin(board)
    tiegame(board)
def main():
    gamechoice = int(input("enter 1 for rps and 2 for ticktacktoe"))
    if gamechoice == 1: #if 1 then run rock paper scissors
        rps()
    elif gamechoice ==2: # if 2 then run the functions for ticktacktoe game
        while flag: 
            tts(board)
    elif gamechoice <1 or gamechoice >2:
        return main()
main()